Adding mongocxx instructions
moveit/warehouse_ros_mongo pull request #3
Opened 2016-09-23 06:49 UTC by ugocupcic

from https://github.com/TheBrewCrew/warehouse_ros_mongo/pull/1

2016-09-23 16:48 UTC, davetcoleman commented on README.md
> +scons --prefix=/usr/local/ --full --use-system-boost --disable-warnings-as-errors
this should also be sudo (unless your on Docker) as already corrected http://moveit.ros.org/install/source/

2016-09-23 16:49 UTC, davetcoleman commented on README.md
> +sudo apt-get install scons
specifying ``cd mongo-cxx-driver`` might be good. too obvious?

2016-09-23 16:49 UTC, davetcoleman commented on README.md
> +## ROS Jade
or Kinetic/or newer.

2016-09-23 16:49 UTC, davetcoleman requested changes

2016-09-26 09:10 UTC, ugocupcic commented
@davetcoleman I addressed all your comments. Cheers

2016-09-26 16:24 UTC, davetcoleman commented
Thanks so much!

2016-09-26 16:26 UTC, merged